bigdatajujuy/bigdatajujuy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
#import personales
from core import views as coreviews

urlpatterns = [
    #Standards
    path('admin/', admin.site.urls),
    url(r'^login/$',auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),

    #Apps Propias
    path('', include('core.urls', namespace='core_app')),
    path('calendario/', include('calendario.urls')),
    path('inscribir/', include('inscripciones.urls')),
    path('novedades/', include('novedades.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bigdatajujuy/core/urls.py
from django.conf.urls import url
from django.urls import path
#Import personales
from . import views

app_name = 'core'
urlpatterns = [
    #Basicas:
    url(r'^$', views.home, name='home'),
    url('^faq/$', views.faq, name='faq'),
    url('^contacto/$', views.contacto, name='contacto'),
    url('^ver_online/$', views.ver_online, name='ver_online'),
    #Conferencia:
    path('conferencias/', views.mostrar_exposiciones, name='mostrar_exposiciones'),
    path('conferencias/<str:str_fecha>', views.mostrar_exposiciones_diario, name='mostrar_exposiciones_diario'),
    path('conferencias/add/<int:inscripto_id>/<int:inscripto_dni>', views.cargar_exposicion, name='cargar_exposicion'),
    #Expositores:
    path('expositores/', views.mostrar_expositores, name='mostrar_expositores'),
    path('expositores/<str:str_fecha>', views.mostrar_expositores_diario, name='mostrar_expositores_diario'),
]

bigdatajujuy/inscripciones/urls.py
from django.conf.urls import url
from django.urls import path
#Import de modulos personales
from . import views

app_name = 'inscripciones'
urlpatterns = [
    path('asistente', views.inscripcion, name='inscripcion'),
    path('expositor', views.inscripcion, name='inscripcion'),

    #Reportes
    path('listado', views.mostrar_inscriptos, name='mostrar_inscriptos'),
    path('tabla', views.mostrar_tabla_inscriptos, name='mostrar_tabla_inscriptos'),
    path('download_excel', views.descargar_inscriptos, name='descargar_inscriptos'),


    #Mails de Activacion
    url(r'^activate/(?P<inscripto_id>[0-9]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    #Subir mail masivos
    url(r'^upload/csv/$', views.upload_csv_mails, name='upload_csv_mails'),

    #Info extra
    path('testmail/<int:msj_id>', views.test_mail, name='test_mail'),
    path('task_progress/<str:queue_name>', views.task_progress, name='task_progress'),
]

bigdatajujuy/inscripciones/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.core.files.storage import FileSystemStorage
from tinymce.models import HTMLField
#Import Personales
from bigdatajujuy.settings import MEDIA_URL

#Creamos choices
CATEGORIA = (
        (1, 'Asistente'),
        (2, 'Expositor'),
    )

DESTINO = (
        (0, 'Solo a Mi > Prueba'),
        (1, 'Usuarios Registrados'),
        (2, 'Inscriptos'),
        (3, 'Correos Validados'),
        (4, 'Correos Sin Validar > Masivo'),
    )

# Create your models here.
class Inscripto(models.Model):
    categoria = models.IntegerField(choices=CATEGORIA, default=1)
    nombres = models.CharField('Nombres', max_length=50)
    apellido = models.CharField('Apellidos', max_length=50)
    descripcion = HTMLField('Acerca de mi', blank=True, null=True)
    foto = models.ImageField('Foto de Perfil', storage=FileSystemStorage(location=MEDIA_URL), blank=True, null=True)
    num_doc = models.CharField('Numero de Documento', max_length=50)
    telefono = models.CharField('Telefono', max_length=20)
    email = models.EmailField('Correo Electronico Personal')
    activo = models.BooleanField('Email Validado', default=False)
    autorizado = models.BooleanField('Autorizado como Expositor', default=False)
    def __str__(self):
        return(self.nombres + ' ' + self.apellido + " (" + self.get_categoria_display() + ")")

class Mails(models.Model):
    email = models.EmailField('Correo Electronico', blank=True, null=True)
    valido = models.BooleanField(default=False)
    def __str__(self):
        return(self.email)

class Mensajes(models.Model):
    nombre = models.CharField('Nombres', max_length=50)
    destinatarios = models.IntegerField(choices=DESTINO, default=0)
    cantidad = models.IntegerField(default=100)
    programar = models.DateTimeField(default=now)
    titulo = models.CharField('Titulo', max_length=50)
    cuerpo = HTMLField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    enviado = models.BooleanField(default=False)

class Progress_Links(models.Model):
    tarea = models.CharField('Tarea', max_length=50)
    inicio = models.DateTimeField(default=now)
    progress_url = models.URLField('Web', blank=True, null=True)

bigdatajujuy/inscripciones/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(50),
            MaxValueValidator(500)
        ]
    )

bigdatajujuy/inscripciones/views.py
from datetime import datetime
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
#Import Particulares
import csv

#Task Manager Models
from background_task.models import Task as bg_Tasks
from background_task.models_completed import CompletedTask as bg_CompletedTask
#decoradores
from django.contrib.admin.views.decorators import staff_member_required

#Import Personales
from .models import Inscripto, Mensajes
from .modelforms import InscriptoForm_asistente, InscriptoForm_expositor
from .tokens import account_activation_token
from .tasks import crear_mails, crear_progress_link

def inscripcion(request):
    tipo = request.path[11:]
    if request.method == 'POST':#Si intenta inscribirse
        if tipo == 'expositor':#Cargamos el objecto form segun tipo de inscripcion
            form = InscriptoForm_expositor(request.POST)
        else: form = InscriptoForm_asistente(request.POST)
        
        if form.is_valid():#Si el formulario se completo correctamente
            to_email = form.cleaned_data.get('email')#Obtenemos el correo
        
            try: inscripto = Inscripto.objects.get(email=to_email) #Chequeamos si no esta inscripto    
            except Inscripto.DoesNotExist:#Si no existe
                inscripto = form.save()#Creamos el inscripto
        
            if not inscripto.activo:#Si el usuario aun no fue activado le vamos a enviar un mail de validacion
                mail_subject = 'Confirma tu Inscripcion a Big Data Jujuy.'
                #Definimos el tipo de mail a enviar
                if tipo == 'expositor': mail_template= 'acc_active_email_exp.html'
                else: mail_template= 'acc_active_email.html'
                #Preparamos el correo electronico
                message = render_to_string(mail_template, {
                    'inscripto': inscripto,
                    'token':account_activation_token.make_token(inscripto),
                })
                #Instanciamos el objeto mail con destinatario
                email = EmailMessage(
                            mail_subject, message, to=[to_email]
                )
                #Enviamos el correo
                email.send()
                #Informamos que el mail fue enviado
                return render(request, 'resultado.html', {'texto': 'Por Favor Confirme la creacion de su cuenta en el correo que recibio', })
            else:
                #informamos que la cuenta ya fue activada.
                return render(request, 'resultado.html', {'texto': 'El mail informado ya fue validado en otra inscripcion', })
            if tipo == 'expositor': inscripto.categoria = 2
            inscripto.save()
    else:#En caso de que ingrese para registrarse
        if tipo == 'expositor': form = InscriptoForm_expositor(initial={'categoria':2,})
        else: form = InscriptoForm_asistente()
    return render(request, 'inscripcion.html', {'form': form, })

def activate(request, inscripto_id, token):
    try:
        inscripto = Inscripto.objects.get(pk=inscripto_id)
    except(TypeError, ValueError, OverflowError, Inscripto.DoesNotExist):
        inscripto = None
    if inscripto is not None and account_activation_token.check_token(inscripto, token):
        inscripto.activo = True
        inscripto.save()
        return render(request, 'resultado.html', {'texto': 'Excelente! Su inscripcion fue validada.', })
    else:
        return render(request, 'resultado.html', {'texto': 'El link de activacion es invalido!', })

def test_mail(request, msj_id):
    mail = Mensajes.objects.get(pk=msj_id)
    return render(request, 'email_base.html', {'mensaje': mail, })

@staff_member_required
def mostrar_inscriptos(request):
    tipo_usuario = [True, False]
    inscriptos = Inscripto.objects.all().order_by('-apellido')
    return render(request, 'inscriptos.html', {'inscriptos': inscriptos, 'tipo_usuario': tipo_usuario })

@staff_member_required
def mostrar_tabla_inscriptos(request):
    tipo_usuario = [True, False]
    inscriptos = Inscripto.objects.all().order_by('-apellido')
    return render(request, 'inscriptos_tabla.html', {'inscriptos': inscriptos, 'tipo_usuario': tipo_usuario })

@staff_member_required
def descargar_inscriptos(request):
    #Obtenemos todos los inscriptos
    inscriptos = Inscripto.objects.all().order_by('-apellido')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="listado_inscriptos.csv"'
    writer = csv.writer(response)
    writer.writerow(['Apellido', 'Nombre','Dni', 'Telefono', 'Correo Electronico', 'Validado'])
    for inscripto in inscriptos:
        writer.writerow([inscripto.apellido, inscripto.nombres, inscripto.num_doc, inscripto.telefono, inscripto.email, inscripto.activo])
    return response

# Create your views here.
@staff_member_required
def upload_csv_mails(request):
    count = 0
    data = {}
    if "GET" == request.method:
        return render(request, "upload_csv.html", data)
    # if not GET, then proceed
    csv_file = request.FILES["csv_file"]
    if not csv_file.name.endswith('.csv'):
        messages.error(request,'File is not CSV type')
        return HttpResponseRedirect(reverse("inscripciones:upload_csv"))
        #if file is too large, return
    if csv_file.multiple_chunks():
        messages.error(request,"Uploaded file is too big (%.2f MB)." % (csv_file.size/(1000*1000),))
        return HttpResponseRedirect(reverse("inscripciones:upload_csv"))
        
    file_data = csv_file.read().decode("utf-8")
    lines = file_data.split("\n")
    #loop over the lines and save them in db. If error , store as string and then display
    #llamar funcion cada 100 mails.
    count = 0
    new_queue = crear_progress_link("CrearMails:"+str(datetime.now()).replace(" ", ">")[0:16])
    while (count + 100) < len(lines):
        crear_mails(lines[count:count+100], schedule=int(count/10), queue=new_queue)
        count+=100
    crear_mails(lines[count:len(lines)], schedule=int(count/10), queue=new_queue)
    return render(request, 'upload_csv.html', {'count': len(lines), 'new_queue': new_queue })

def task_progress(request, queue_name):
    tareas_en_progreso = bg_Tasks.objects.filter(queue= queue_name)
    tareas_terminadas = bg_CompletedTask.objects.filter(queue= queue_name)
    return render(request, 'task_progress.html', {'tarea_queue': queue_name, 
                                                'tareas_totales': (len(tareas_en_progreso)+len(tareas_terminadas)) ,
                                                'tareas_en_cola': len(tareas_en_progreso), 
                                                'tareas_terminadas': len(tareas_terminadas),
                                                "refresh": True })

bigdatajujuy/inscripciones/templates/acc_active_email.html
{% autoescape off %}
Bienvenido {{ inscripto.nombres }} {{ inscripto.apellido }},
Dni: {{ inscripto.num_doc }}
Teléfono: {{ inscripto.telefono }}
Por favor ingresa a este link para confirmar tu inscripción a Jujuy Big Data Summit 2019,
Que se realizará en San Salvador de Jujuy:
http://bigdata.jujuydigital.com.ar/inscribir/activate/{{inscripto.pk}}/{{token}}
A través de este correo, recibirás las notificaciones y noticias importantes del evento.
{% endautoescape %}

bigdatajujuy/inscripciones/templates/acc_active_email_exp.html
{% autoescape off %}
Bienvenido {{ inscripto.nombres }} {{ inscripto.apellido }},
Dni: {{ inscripto.num_doc }}
Teléfono: {{ inscripto.telefono }}
Por favor ingresa a este link para confirmar tu inscripción a Jujuy Big Data Summit 2019,
Que se realizará en San Salvador de Jujuy:
http://bigdata.jujuydigital.com.ar/inscribir/activate/{{inscripto.pk}}/{{token}}
A través de este correo, recibirás las notificaciones y noticias importantes del evento.


A su vez, en el siguiente link podra ingresar multiples veces para cargar las exposiciones que propone realizar:
http://bigdata.jujuydigital.com.ar/conferencias/add/{{inscripto.pk}}/{{inscripto.num_doc}}
{% endautoescape %}

bigdatajujuy/inscripciones/templates/email_base.html
<img src="http://bigdata.jujuydigital.com.ar/static/img/header.png" alt="Logo_bigdatajujuy" width="100%"/>

{{mensaje.cuerpo|safe}}

bigdatajujuy/inscripciones/templates/inscripcion.html
{% extends 'base.html' %}

{% block title %}Inscripcion{% endblock %}

{% block content %}
<section class="inscripcion">  
  <div class="inscripcion-container">
    <h2>Inscribase al Evento Jujuy Big Data Summit</h2>
      <form method="post">
        {% csrf_token %}
        {% for field in form %}
          <div class="input-group">
            {{ field.label_tag }}<br>
            {{ field }}
            {% for error in field.errors %}
              <p style="color:black">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
        <button type="submit">Registrarse</button>
      </form>
  </div>
</section>
{% endblock %}

bigdatajujuy/inscripciones/templates/inscriptos.html
{% extends 'base.html' %}

{% block title %}Resultado{% endblock %}

{% block content %}
  <div class="linea_inscripto">
    <div class="linea_nombre">
      <h1><b>Listado de Incriptos</b></h1>
    </div>
    <div class="linea_telefono">
      <a href="tabla">Ver en tabla simple</a>
    </div>
    <div class="linea_email">
      <a href="download_excel">Descargar Excel</a>
    </div>
  </div>
  <div class="inscriptos">
    {% for tipo in tipo_usuario %}
      {% if tipo %}
        <h2><b>Inscriptos Validados</b></h2>
      {% else %}
        <hr>
        <h2><b>Inscriptos sin Validar</b></h2>
      {%endif%}
      <ul class="list-unstyled">
        <li>
          <div class="linea_inscripto">
            <div class="linea_relleno"></div>
            <div class="linea_nombre">
              <b>Nombre y Apellido</b>
            </div>
            <div class="linea_documento">
              <b>Documento</b>
            </div>
            <div class="linea_telefono">
              <b>Telefono</b>
            </div>
            <div class="linea_email">
              <b>Correo Electronico</b>
            </div>
            <div class="linea_relleno"></div>
          </div>
        </li>      
      {%for inscripto in inscriptos %}
        {% if tipo == inscripto.activo %}
          <li>
            <div class="linea_inscripto">
              <div class="linea_relleno"></div>
              <div class="linea_nombre">
                {{inscripto.apellido}}, {{inscripto.nombres}}
              </div>
              <div class="linea_documento">
                {{inscripto.num_doc}}
              </div>
              <div class="linea_telefono">
                {{inscripto.telefono}}
              </div>
              <div class="linea_email">
                {{inscripto.email}}
              </div>
              <div class="linea_relleno"></div>
            </div>
          </li>
        {%endif%}
      {%endfor%}
      </ul>
    {%endfor%}
  </div>
{% endblock %}

bigdatajujuy/inscripciones/templates/inscriptos_tabla.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }

      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }

      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
  </head>
  <body>
    {% for tipo in tipo_usuario %}
      {% if tipo %}
        <h2><b>Inscriptos Validados</b></h2>
      {% else %}
        <hr>
        <h2><b>Inscriptos sin Validar</b></h2>
      {%endif%}
      <table style="width:100%">
        <tr>
            <th>Nombre y Apellido</th>
            <th>Documento</th>
            <th>Telefono</th>
            <th>Correo Electronico</th>
        </tr>      
      {%for inscripto in inscriptos %}
        {% if tipo == inscripto.activo %}
          <tr>
            <th>{{inscripto.apellido}}, {{inscripto.nombres}}</th>
            <th>{{inscripto.num_doc}}</th>
            <th>{{inscripto.telefono}}</th>
            <th>{{inscripto.email}}</th>
          </tr>
        {%endif%}
      {%endfor%}
      </table>
    {%endfor%}

  </body>
</html>

bigdatajujuy/inscripciones/templates/resultado.html
{% extends 'base.html' %}

{% block title %}Resultado{% endblock %}

{% block content %}
<section class="inscripcion">  
  <div class="respuesta-container">
    <h2>{{texto}}</h2>
  </div>
</section>
{% endblock %}

bigdatajujuy/inscripciones/templates/task_progress.html
{% extends 'base.html' %}
 
{% block title %}Progreso Tarea{% endblock %}

{% block content %}
<section class="progreso">
    <div class="progreso-container">
        <h2>Progresso de la tarea: {{ tarea_queue }}</h2>
        <p> Tareas en Cola: {{ tareas_en_cola }} </p>
        <p> Tareas Finalizadas: {{ tareas_terminadas }} </p>
        <progress class="barra" value="{{ tareas_terminadas }}" max="{{ tareas_totales }}"></progress>
    </div>
</section>
{% endblock %}

bigdatajujuy/inscripciones/templates/upload_csv.html
{% extends 'base.html' %}
{% block content %}
    {% if count %}
        <p>Se lograron Cargar {{ count }} Correos que comenzaran a guardarse en la lista del boletin. </p>
        <P>Puede observar el avance del proceso <a href='/inscribir/task_progress/{{ new_queue }}'>aqui</a></p>
    {% else %}
        <form action="{% url "inscripciones:upload_csv_mails" %}" method="POST" enctype="multipart/form-data" class="form-horizontal"> 
        {% csrf_token %}
        <div class="form-group">
            <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
            <div class="col-md-8">
                <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
            </div>                    
        </div>
        <div class="form-group">                    
            <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
                <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
            </div> 
        </div>
        </form>
    {% endif %}
{% endblock %}